### ISSUE TITLE
Packer installation fail

### ISSUE THREAD

**Issue by mortezadadgar** [ellisonleao/glow.nvim#28]
Already if I try to install like mentioned in reamdme, :PackerSync fail to install the plugin which occurs bc packer haven't loaded plugin so executing GlowInstall command fail for packer
I can open markdown and manually execute GlowInstall this way works but it's not automated

**Comment by dominikhaid** [comment]
Same here system is  Debian 11.
I get an error after :PackerInstall if i use  use {"npxbr/glow.nvim", run = "GlowInstall"}.
If i use  {"npxbr/glow.nvim"} everything runs fine but there is not :Glow command in nvim so i cant use it. Its a bit sad i have glow already on my system so the plug should not have to install it but nothing works...

**Comment by ellisonleao** [comment]
What neovim version are you guys using?

**Comment by mortezadadgar** [comment]
> What neovim version are you guys using?

0.5 stable

**Comment by ellisonleao** [comment]
@dominikhaid @mortezadadgar can you guys provide more info, like the error you guys are having and some configuration to reproduce it?

**Comment by dominikhaid** [comment]
For me it is when I use run = "GlowInstall" with packer. The error I get is just "Glow could not be installed". When is install the plug without the run argument everything goes well. And the Plugin is working well. Maybe it's because glow is already installed at my system don't know.

**Comment by ellisonleao** [comment]
>I didn't even realized that :Glow is just available in .MD files. That confused me even a bit.

What caused the confusion?

**Comment by dominikhaid** [comment]
Nothing special. It's somewhere in the doc's and I didn't recognized it. Maybe it was just the fact that I was new to Nvim and got that error and the command :Glow was not found on startup. But a bit of research just solved it for me. So for me it's closed.

**Comment by ellisonleao** [comment]
Guys i've fixed the GlowInstall command creation now and we had an update also in the install script. Can you guys pull latest and try again please?

**Comment by mortezadadgar** [comment]
> Guys i've fixed the GlowInstall command creation now and we had an update also in the install script. Can you guys pull latest and try again please?

packer installation still fails 
![image](https://user-images.githubusercontent.com/27911493/130271856-ed1eeaa2-2f81-4f5c-9456-db6890dea013.png)
it's just bad for UX not actually means plugin installation has failed, I can't run :GlowInstall on any other file than *.md maybe that's why it fails

**Comment by dominikhaid** [comment]
Install worked for me now without any errors.

**Comment by ellisonleao** [comment]
>it's just bad for UX not actually means plugin installation has failed, I can't run :GlowInstall on any other files than *.md maybe that's why it fails

are you sure you have the latest code? the glowinstall command is set after you load the plugin, for every filetype

**Comment by mortezadadgar** [comment]
> > it's just bad for UX not actually means plugin installation has failed, I can't run :GlowInstall on any other files than *.md maybe that's why it fails
> 
> are you sure you have the latest code? the glowinstall command is set after you load the plugin, for every filetype. Also I see you are still using the old route. I've change the plugin address to my username. Can you update to `ellisonleao/glow.nvim` as well please?

yeah I'm using the latest code
```
use {
  "ellisonleao/glow.nvim",
  run = "GlowInstall"
}
```
removed plugin and installed multiple times still fails

**Comment by jc00ke** [comment]
```lua
use {
  "...",
  run = function ()
    require('glow').download_glow()
  end
}
```

What happens if you call the Lua function directly from the `run` callback as a `function`? I'm not sure if that'll work (on phone) but it's worth a try.

**Comment by mortezadadgar** [comment]
@jc00ke works this way

**Comment by gabojkz** [comment]
It is not working for me using:
NVIM v0.5.0-dev
Same error using GlowInstall but for Plug this time,

I am guessing the solution is to make the same as:
```
use {
  "ellisonleao/glow.nvim",
  run = function ()
    require('glow').download_glow()
  end
}
```

but this time for vimPlug any idea how to do it?

**Comment by ellisonleao** [comment]
guys, a new fix for the installation was just pushed. Can you guys pull latest and try again please?

**Comment by gabojkz** [comment]
<img width="830" alt="Screenshot 2021-08-24 at 15 34 21" src="https://user-images.githubusercontent.com/11217929/130636100-2aa8f8d3-9871-42f5-b716-7b46c5234365.png">
Still same problem for me

**Comment by ellisonleao** [comment]
hey @gabojkz are you sure you have latest code?

**Comment by Pocco81** [comment]
I'm experiencing the same issue too. The installation failed using the packer snippet from the README. I also tried it without the `run = "..."` and still, it said that it successfully installed glow, yet running `:Glow` failed. However, grabbing `glow` from the AUR worked fine for me.

**Comment by ellisonleao** [comment]
I've removed the suggestions about GlowInstall in the setup step for plugins. It should work after installing the main plugin
